### ISSUE TITLE
ValueError: embedded null character when using copy to clipboard

### ISSUE THREAD

**Issue by Bakuryu** [codetorex/spritex#1]
When I try to copy a region to clipboard I get this error.

**Comment by codetorex** [comment]
I am unable to replicate this problem, can you provide some more details?
Like;
What operating systems are you using?
What clipboard system does kivy uses? (When app is starting, it will provide some information. It will be better if you can paste them all here or at least paste the line that starts with `[INFO   ] [Clipboard   ]`)

**Comment by Bakuryu** [comment]
I'm using Windows 7 Professional.
It uses winctypes for the clipboard system
Here is a picture of the output
![capture](https://user-images.githubusercontent.com/3741180/32960539-315711d2-cb93-11e7-9a14-772b95ba4f63.PNG)

**Comment by tbarusseau** [comment]
Hello,

I'm using Windows 10, and I have the same issue.

Crash stack trace:

```
(serpent) D:\SerpentAI\datasets\collect_frames>spritex  frame_365f0865-c022-4114-9325-06da8c202f60.png
[INFO   ] [Logger      ] Record log in C:\Users\Nepho\.kivy\logs\kivy_17-11-28_3.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Clipboard   ] Provider: winctypes
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 388.13'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 970/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
Image set
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "d:\users\nepho\anaconda3\envs\serpent\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "D:\Users\Nepho\Anaconda3\envs\serpent\Scripts\spritex.exe\__main__.py", line 9, in <module>
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\editor\__init__.py", line 34, in execute
     SpriteEditorApp().run()
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
     self._mainloop()
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\core\window\__init__.py", line 1188, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\core\window\__init__.py", line 1204, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\uix\widget.py", line 457, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8191)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
   File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
   File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\editor\__init__.py", line 208, in copy_region_press
     Clipboard.copy(text)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\core\clipboard\__init__.py", line 73, in copy
     self._copy(data)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\core\clipboard\__init__.py", line 87, in _copy
     self.put(data, self._clip_mime_type)
   File "d:\users\nepho\anaconda3\envs\serpent\lib\site-packages\kivy\core\clipboard\clipboard_winctypes.py", line 55, in put
     msvcrt.wcscpy_s(c_wchar_p(hCd), len(text), c_wchar_p(text))
 ValueError: embedded null character
```

Could it be because of a `\0` terminating the string? I don't have much tools to debug on Windows, unfortunately.

**Comment by codetorex** [comment]
Just tested on Windows 8.1 and Anaconda3 4.4.0, Python 3.6.2 and still cannot reproduce the bug. There is no null termination etc. It is normal formatted string. 

```
        text = f"\"REGION\": ({int(region.sel_y)}, {int(region.sel_x)}, {int(region.sel_y + region.sel_height)}, {int(region.sel_x + region.sel_width)})"
        Clipboard.copy(text)
```

I noticed both of you using Python 3.6.3 though. So I just installed latest Anaconda 5.0.1 and tested with Python 3.6.3 and could reproduce bug now. Then created a new environment with 3.6.2 and bug isn't happening. So it is something with Python version and it is only happening in Windows. I dunno how people deal with this kind of problem :) Kivy might need rebuilding or something. Meanwhile you can use spritex with new environment;

```
conda create --name spritex python=3.6.2
activate spritex
pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew numpy kivy pillow spritex
```

**Comment by tbarusseau** [comment]
Thanks for the fix, @codetorex, I'll try it when I have some free time.

**Comment by tbarusseau** [comment]
Thanks @codetorex :smile:
